description: CovidInfo es una aplicación móvil para Android muy simple, que proporciona información actualizada, de manera cuantitativa y gráfica sobre la evolución de la pandemia COVID-19.
theme: jekyll-theme-cayman
title: CovidInfo
